[package]
name = "normalduck/dialogue"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A flexible dialogue module made with Fusion"

[dependencies]
Fusion = "elttob/fusion@0.2.0"
ByteNet = "ffrostflame/bytenet@0.4.5"
TableUtil = "sleitnick/table-util@1.2.1"

#PLEASE REMOVE THE COMPILE FOLDER OUT OF PACKAGES BEFORE INSTALLING. IT WILL REMOVE SUBFILES AND IRRVERSIBLE